config/routes.rb
Pironimo::Application.routes.draw do

  devise_for :users
  
  root :to => 'static#index'
  
  resources :pages
  resources :posts
  resources :comments
  

end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  
  # See https://github.com/benedikt/mongoid-tree#readme
  include Mongoid::Tree
  include Mongoid::Tree::Ordering   # adds a 'position' field to the model
  include Mongoid::Tree::Traversal
  
  field :body, :type => String
  
  belongs_to :post
  belongs_to :user
  
  validates_presence_of :post
  validates_presence_of :user
end

app/models/page.rb
class Page
  include Mongoid::Document
  include Mongoid::Timestamps
    
  field :slug, :type => String
  field :title, :type => String
  
  has_many :posts
  
  validates_presence_of :slug
  validates_presence_of :title
  
  validates_uniqueness_of :slug
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps

  field :body, :type => String

  belongs_to :page
  belongs_to :user
  has_many :comments
  
  validates_presence_of :page
  validates_presence_of :user
end

app/models/user.rb
class User
  include Mongoid::Document
  
  devise :database_authenticatable, :registerable, :confirmable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable
  
  attr_accessible :name, :initials, :tip_css,
                  :email, :password, :password_confirmation, :remember_me
  
  field :name, :type => String
  field :initials, :type => String
  field :tip_css, :type => String
  
  has_many :posts
  has_many :comments
  
  validates_presence_of :name
  validates_presence_of :initials
  validates_uniqueness_of :initials, :email, :case_sensitive => false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    redirect_to page_path('front')
  end
  
  def show
    @page = Page.where(:slug => params[:id]).first
    render :text => "Aieeee!" if @page == nil
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @page = Page.where(:slug => params[:page_slug]).first
    @post = @page.posts.build
    @post.body = params[:body]
    @post.save
    current_user.posts << @post
    current_user.save
    redirect_to page_path(@page.slug)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.haml
!!! 5
%html
  %head
    %title= yield(:title)
    = csrf_meta_tag
    /[if lt IE 9]
      = javascript_include_tag 'html5'
    = stylesheet_link_tag 'compiled/screen'
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Geo'
    = javascript_include_tag :defaults
  %body.pironimo-main.bp
    - flash.each do |name, msg|
      = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
    = yield
  

app/views/pages/show.html.haml
= content_for :title, "p1r0n1m0: #{@page.title}"
%h1= @page.title
= form_tag(posts_path) do
  = text_area_tag(:body, "", :size => "100x6")
  = hidden_field_tag(:page_slug, @page.slug)
  = submit_tag "New Post!"
%ul.posts
  - @page.posts.each do |post|
    %li
      %p.body(style="#{post.user.tip_css}")= post.body
      %p.initials= post.user.initials